---
- name: Make sure that the homebrew casks are installed.
  community.general.homebrew_cask:
    name:
      - 1password
      - alfred
      - alt-tab
      - appcleaner
      - dotnet-sdk
      - google-chrome
      - iina
      - iterm2
      - itsycal
      - microsoft-auto-update
      - microsoft-office
      - parallels
      - parallels-access
      - parallels-toolbox
      - podman-desktop
      - raspberry-pi-imager
      - rider
      - signal
      - spotify
      - telegram
      - topnotch
      - transmission
      - visual-studio-code
      - warp
      - whatsapp
    state: present

- name: Ensure that the homebrew formulae are installed.
  community.general.homebrew:
    name:
      - git
      - mas
      - neovim
      - npm
      - podman
      - podman-compose
      - wget
    state: present

- name: Update homebrew and upgrade all packages.
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
