---
- name: Install applications from the App Store
  community.general.mas:
    id: "{{ item.id | int }}"
    state: "{{ item.state }}"
  loop: "{{ applications_app_store }}"

- name: Upgrade all installed Mac App Store apps
  community.general.mas:
    upgrade_all: true
