---
- name: Make sure that the homebrew casks are installed.
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ applications_casks }}"

- name: Ensure that the homebrew formulae are installed.
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ applications_brew }}"

- name: Update homebrew and upgrade all packages.
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
