---
- name: Install applications from the App Store
  community.general.mas:
    id: "{{ item.id }}"
    state: "{{ item.state }}"
  loop: "{{ store_apps }}"

- name: Upgrade all installed Mac App Store apps
  community.general.mas:
    upgrade_all: true
