---
- name: Set Finder view mode.
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
  notify: "{{ item.notify }}"
  loop: "{{ defaults_values }}"

- name: Update git global configuration and sets the `user.name` option.
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_config_username }}"
- name: Update git global configuration and sets the `user.email` option.
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_config_email }}"
- name: Update git global configuration and sets the `defaultBranch` option.
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: "{{ git_config_default_branch }}"
