---
galaxy_info:
  author: Hugo Paredes
  description: Set macOS defaults

  license: Apache-2.0

  min_ansible_version: "2.1"

  platforms:
    - name: macOS
      versions:
        - all

  galaxy_tags: []

dependencies: []
